# Generated by Django 5.0.1 on 2024-02-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('published_at', models.DateTimeField()),
                ('content', models.TextField()),
                ('urlToImage', models.URLField(blank=True, null=True)),
                ('source', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('category', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
