# Generated by Django 5.0.1 on 2024-02-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_remove_newsarticle_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
