# Generated by Django 5.0.1 on 2024-02-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_alter_newsarticle_author_alter_newsarticle_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='urlToImage',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
