# Generated by Django 5.0.1 on 2024-02-09 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_alter_newsarticle_url_alter_newsarticle_urltoimage'),
    ]

    operations = [
    ]
